excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - /Users/ahmedabdallah/Documents/APPS/WeatherApp/R.generated.swift
  - /Users/ahmedabdallah/Documents/APPS/Joker/Joker/Networking/ServiceConnector.swift
line_length:
  - 300 # warning
  - 600 # error
disabled_rules: # rule identifiers to exclude from running
  - file_length
