excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - /Users/ahmedabdallah/Documents/APPS/WeatherApp/R.generated.swift
line_length:
  - 300 # warning
  - 600 # error
disabled_rules: # rule identifiers to exclude from running
  - file_length
  - syntactic_sugar
  - void_return
  - legacy_constructor
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
